# HTTP(S) is part of the executable, not a subprocess or a separately installed DLL.
# Dependencies are pinned and hash-checked; FetchContent source overrides allow offline builds.
include(FetchContent)
if(POLICY CMP0135)
    cmake_policy(SET CMP0135 NEW)
endif()

function(foxlang_networking)
    set(CMAKE_POLICY_DEFAULT_CMP0077 NEW)
    set(BUILD_TESTING OFF)
    set(BUILD_EXAMPLES OFF)
    set(BUILD_SHARED_LIBS OFF)
    set(BUILD_STATIC_LIBS ON)
    set(BUILD_CURL_EXE OFF)
    set(BUILD_LIBCURL_DOCS OFF)
    set(BUILD_MISC_DOCS OFF)
    set(ENABLE_CURL_MANUAL OFF)
    set(CURL_DISABLE_INSTALL ON)
    set(CURL_ENABLE_EXPORT_TARGET OFF)
    set(CURL_STATIC_CRT ON)
    set(PICKY_COMPILER OFF)
    set(HTTP_ONLY ON)
    set(CURL_ZLIB OFF CACHE STRING "No extra shared compression libraries" FORCE)
    set(CURL_BROTLI OFF CACHE STRING "No extra shared compression libraries" FORCE)
    set(CURL_ZSTD OFF CACHE STRING "No extra shared compression libraries" FORCE)
    set(USE_LIBIDN2 OFF)
    set(USE_NGHTTP2 OFF)
    set(CURL_USE_LIBPSL OFF)
    set(CURL_USE_LIBSSH2 OFF)
    set(CURL_USE_OPENSSL OFF)
    set(CURL_USE_PKGCONFIG OFF)
    set(CURL_DISABLE_NETRC ON)
    set(CURL_CA_BUNDLE none CACHE STRING "Select the recipient CA store at runtime" FORCE)
    set(CURL_CA_PATH none CACHE STRING "Select the recipient CA store at runtime" FORCE)
    if(WIN32)
        set(CURL_USE_SCHANNEL ON)
        set(CURL_USE_MBEDTLS OFF)
    else()
        set(CURL_USE_MBEDTLS ON)
        set(ENABLE_PROGRAMS OFF CACHE BOOL "Do not build Mbed TLS utilities" FORCE)
        set(ENABLE_TESTING OFF CACHE BOOL "Run FoxLang integration tests, not vendor test suites" FORCE)
        set(MBEDTLS_FATAL_WARNINGS OFF)
        set(DISABLE_PACKAGE_CONFIG_AND_INSTALL ON)
        FetchContent_Declare(mbedtls
            URL https://github.com/Mbed-TLS/mbedtls/releases/download/mbedtls-3.6.7/mbedtls-3.6.7.tar.bz2
            URL_HASH SHA256=a7e8bcbec0e6f761b4af24f25677626b35f762f68eef79c08677a363212d11f6)
        FetchContent_MakeAvailable(mbedtls)
        set(MBEDTLS_INCLUDE_DIR "${mbedtls_SOURCE_DIR}/include")
        set(MBEDTLS_LIBRARY mbedtls)
        set(MBEDX509_LIBRARY mbedx509)
        set(MBEDCRYPTO_LIBRARY mbedcrypto)
        set(HAVE_MBEDTLS_DES_CRYPT_ECB 1)
    endif()
    FetchContent_Declare(curl
        URL https://curl.se/download/curl-8.22.0.tar.xz
        URL_HASH SHA256=f7ef3ae8a22e521f289803fe93543eb64c329b58aa73a9e224dfd915a2a5f4f7)
    FetchContent_MakeAvailable(curl)
    target_link_libraries(foxlang_core PRIVATE CURL::libcurl_static)
    if(WIN32)
        target_link_libraries(foxlang_core PRIVATE ws2_32)
    endif()

    # License texts travel inside every standalone executable.
    file(READ "${curl_SOURCE_DIR}/COPYING" notices)
    set(notices "libcurl 8.22.0\n${notices}")
    if(NOT WIN32)
        file(READ "${mbedtls_SOURCE_DIR}/LICENSE" tls_license)
        string(APPEND notices "\nMbed TLS 3.6.7\n${tls_license}")
    endif()
    file(WRITE "${CMAKE_CURRENT_BINARY_DIR}/generated/NetworkLicenses.h.in"
        "#pragma once\ninline const char* networkLicenses() { return R\"FOXLICENSE(${notices})FOXLICENSE\"; }\n")
    configure_file("${CMAKE_CURRENT_BINARY_DIR}/generated/NetworkLicenses.h.in"
                   "${CMAKE_CURRENT_BINARY_DIR}/generated/NetworkLicenses.h" COPYONLY)
endfunction()

foxlang_networking()
